'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.510
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.510.
'
Namespace com.swanandmokashi.www
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="StockQuotesSoap", [Namespace]:="http://swanandmokashi.com/")>  _
    Public Class StockQuotes
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://www.swanandmokashi.com/HomePage/WebServices/StockQuotes.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://swanandmokashi.com/GetStockQuotes", RequestNamespace:="http://swanandmokashi.com/", ResponseNamespace:="http://swanandmokashi.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStockQuotes(ByVal QuoteTicker As String) As <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> Quote()
            Dim results() As Object = Me.Invoke("GetStockQuotes", New Object() {QuoteTicker})
            Return CType(results(0),Quote())
        End Function
        
        '<remarks/>
        Public Function BeginGetStockQuotes(ByVal QuoteTicker As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetStockQuotes", New Object() {QuoteTicker}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetStockQuotes(ByVal asyncResult As System.IAsyncResult) As Quote()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Quote())
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://swanandmokashi.com/")>  _
    Public Class Quote
        
        '<remarks/>
        Public CompanyName As String
        
        '<remarks/>
        Public StockTicker As String
        
        '<remarks/>
        Public StockQuote As String
        
        '<remarks/>
        Public LastUpdated As String
        
        '<remarks/>
        Public Change As String
        
        '<remarks/>
        Public OpenPrice As String
        
        '<remarks/>
        Public DayHighPrice As String
        
        '<remarks/>
        Public DayLowPrice As String
        
        '<remarks/>
        Public Volume As String
        
        '<remarks/>
        Public MarketCap As String
        
        '<remarks/>
        Public YearRange As String
    End Class
End Namespace
