'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.510
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.510.
'
Namespace Chapter16
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="DemoSoap", [Namespace]:="http://tempuri.org/WebServiceDemo/Demo")>  _
    Public Class Demo
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://192.168.1.180/WebServiceDemo/Demo.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebServiceDemo/Demo/CalcPay", RequestNamespace:="http://tempuri.org/WebServiceDemo/Demo", ResponseNamespace:="http://tempuri.org/WebServiceDemo/Demo", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CalcPay(ByVal Hours As Single, ByVal Rate As Single) As Single
            Dim results() As Object = Me.Invoke("CalcPay", New Object() {Hours, Rate})
            Return CType(results(0),Single)
        End Function
        
        '<remarks/>
        Public Function BeginCalcPay(ByVal Hours As Single, ByVal Rate As Single, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CalcPay", New Object() {Hours, Rate}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndCalcPay(ByVal asyncResult As System.IAsyncResult) As Single
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Single)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebServiceDemo/Demo/StructureDemo", RequestNamespace:="http://tempuri.org/WebServiceDemo/Demo", ResponseNamespace:="http://tempuri.org/WebServiceDemo/Demo", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function StructureDemo(ByVal ListingNumber As String) As ListingSpecs
            Dim results() As Object = Me.Invoke("StructureDemo", New Object() {ListingNumber})
            Return CType(results(0),ListingSpecs)
        End Function
        
        '<remarks/>
        Public Function BeginStructureDemo(ByVal ListingNumber As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("StructureDemo", New Object() {ListingNumber}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndStructureDemo(ByVal asyncResult As System.IAsyncResult) As ListingSpecs
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ListingSpecs)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebServiceDemo/Demo/ClassDemo", RequestNamespace:="http://tempuri.org/WebServiceDemo/Demo", ResponseNamespace:="http://tempuri.org/WebServiceDemo/Demo", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ClassDemo(ByVal ListingNumber As String) As DemoClass
            Dim results() As Object = Me.Invoke("ClassDemo", New Object() {ListingNumber})
            Return CType(results(0),DemoClass)
        End Function
        
        '<remarks/>
        Public Function BeginClassDemo(ByVal ListingNumber As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ClassDemo", New Object() {ListingNumber}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndClassDemo(ByVal asyncResult As System.IAsyncResult) As DemoClass
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),DemoClass)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebServiceDemo/Demo/DsDemo", RequestNamespace:="http://tempuri.org/WebServiceDemo/Demo", ResponseNamespace:="http://tempuri.org/WebServiceDemo/Demo", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DsDemo() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("DsDemo", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginDsDemo(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DsDemo", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndDsDemo(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/WebServiceDemo/Demo")>  _
    Public Class ListingSpecs
        
        '<remarks/>
        Public ListingNumber As String
        
        '<remarks/>
        Public Address As String
        
        '<remarks/>
        Public Rooms As Integer
        
        '<remarks/>
        Public Bedrooms As Single
        
        '<remarks/>
        Public Baths As Single
        
        '<remarks/>
        Public Size As Integer
        
        '<remarks/>
        Public Price As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/WebServiceDemo/Demo")>  _
    Public Class DemoClass
        
        '<remarks/>
        Public ListingNumber As String
        
        '<remarks/>
        Public Address As String
        
        '<remarks/>
        Public Rooms As Integer
        
        '<remarks/>
        Public Bedrooms As Single
        
        '<remarks/>
        Public Baths As Single
        
        '<remarks/>
        Public Size As Integer
        
        '<remarks/>
        Public Price As String
    End Class
End Namespace
